### PR TITLE
Added Google Map and Added link from index.html to contact.html

### PR DESCRIPTION
**Pull request by luiseduardocamacho**

### CODE REVIEW

**Comment by Tonkpils** [comment]
I'll take a better look at this in the morning. It looks really good. The only thing that popped out was the difference in variable naming in the map js script from `camelCase` to `snake_case`, I believe in JavaScript camelCase is the standard. Can you add commit that fixes this? Also, from CSS best practices I believe that ids shouldn't be used for styling. Classes are best suited for it. Could you change it so that the map modal is styled using a class? What do you think?

**Comment by luiseduardocamacho** [comment]
Ok Leo, thanks. I'll work on it and make a new pull request when it is
done.

**Comment by Tonkpils** [comment]
@tuconexionusa you don't have to make a new pull request. Just commit the new changes and push them to the remote and this Pull request will be updated. Let me know if you have any issues. :+1: Thanks for the contributions!

**Comment by Tonkpils** [comment]
@tuconexionusa How's it going are you having any problems? Keep me updated whenever you have time.

**Comment by Tonkpils** [comment]
Awesome this looks great! Thanks!

**Pull request merged**
